runtime: go111

handlers:
- url: /static
  static_dir: static
- url: /v2/
  script: auto
  secure: always
- url: /auth/
  script: auto
  secure: always
- url: .*
  static_files: templates/gen/index.html
  upload: templates/gen/index.html
  secure: always

env_variables:
  DATASTORE_PROJECT_ID: metahub
