steps:
#- name: "ubuntu"
#  args: ["sed", "-i", "-e", "s/__CACHE_NAME__/$BUILD_ID/", "client/worker.js"]
- name: "gcr.io/cloud-builders/npm"
  dir: "ui"
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "app.yaml", "index.yaml", "--version=1"]
timeout: "1600s"